[package]
name = "cattix-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cattix-core = { path = "../cattix-core" }
clap = { version = "4", features = ["derive"] }
iocraft = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smol = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
