[package]
name = "cattix-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cattix-nix = { path = "../cattix-nix" }
cattix-transport = { path = "../cattix-transport" }
cattix-utils = { path = "../cattix-utils" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "time"] }
zeronine_probes = { git = "ssh://git@github.com/Code-Growers/Zeronine.git", rev = "b58e533a8e158a4f3961be104686000ab53e5ef7", package = "zeronine_probes", default-features = false, features = ["command", "grpc", "http", "tcp"] }
